DROP TABLE IF EXISTS Characters;
CREATE TABLE Characters (
	ID	INTEGER NOT NULL UNIQUE,
	Name	TEXT NOT NULL UNIQUE,
	Icon	TEXT,
	PRIMARY KEY(ID)
);



/* CREATE TABLE Stances (
  MoveID INTEGER,
  Stance TEXT
); */

DROP TABLE IF EXISTS Moves;
CREATE TABLE Moves (
	ID	INTEGER UNIQUE,
	Command	TEXT,
	Character	TEXT,
    CharacterID INTEGER,
	MoveCategory	TEXT,
	MoveName	TEXT,
	Stance	TEXT,
	HitLevel	TEXT,
	Impact	REAL,
	Damage	TEXT,
	DamageDec	INTEGER,
	Block	TEXT,
	BlockDec	INTEGER,
	Hit	TEXT,
	HitDec	INTEGER,
	CounterHit	TEXT,
	CounterHitDec	INTEGER,
	GuardBurst	INTEGER,
	Notes	TEXT,
	isGI	INTEGER NOT NULL DEFAULT 0,
	isUB	INTEGER NOT NULL DEFAULT 0,
	isLH	INTEGER NOT NULL DEFAULT 0,
	isSS	INTEGER NOT NULL DEFAULT 0,
	isBA	INTEGER NOT NULL DEFAULT 0,
	isTH	INTEGER NOT NULL DEFAULT 0,
	isRE	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY(ID)
);


